Adding voting and improving tools

diff --git a/tools/ask b/tools/ask
--- a/tools/ask
+++ b/tools/ask
@@ -70,10 +70,20 @@ uuid=$(uuidgen | tr 'A-Z' 'a-z')
 match_json='[{"id": "'${uuid}'","asked": "'${asked}'"}]'
 json='{"id": "'${uuid}'", "asked": "'${asked}'","decision": "'$decision'", "description": "'$description'", "controversial": '$controversy', "question": "'${question}'","time": "'${timestamp}'"}'
 
+stat_json='{"id": "'${uuid}'", "simple": {"yes": 0, "no": 0}}'
+
 echo ${json} | jq
 
 echo "This ok? (hit enter if yeah, hit ctrl-c if nah)"
 read
 
 echo ${json} | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-questions/${uuid}
+
+if [ $? -ne 0 ]; then
+  echo "ERROR: Failed to save question! Please try again (soz)."
+  exit 1
+fi
+
+echo ${stat_json} | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-statistics/${uuid}
+
 firebase --project ${project} --token ${token} database:get /v0/live-matches/${match}/questions | jq ". |= .+ $match_json" | firebase --non-interactive --project ${project} --token ${token} database:set -y /v0/live-matches/${match}/questions
